//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsHotel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reservation
    {
        public System.Guid Id { get; set; }
        public System.Guid HotelId { get; set; }
        public System.Guid GuestId { get; set; }
        public System.Guid RoomId { get; set; }
        public System.DateTime DateArrival { get; set; }
        public System.DateTime DateDeparture { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.DateTime DateUpdated { get; set; }
    
        public virtual Guest Guest { get; set; }
        public virtual Hotel Hotel { get; set; }
        public virtual Room Room { get; set; }
    }
}
